name: KBVE Auto Alpha <-> Beta Pull Request

on:
  push:
    branches:
    - "alpha"
  
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request
        uses: actions/checkout@v3
        
      - name: auto-deploy
        uses: diillson/auto-pull-request@v1.0.1
        with:
            destination_branch: "beta"                       
            pr_title: "Pulling ${{ github.ref }} into beta"  
            pr_body: |                                      
              :crown: *An automated PR*
              Migrating from `alpha` stage to `beta` stage.
              - - -
                This stage is for security checks and general production prep.
              - - -
                For Security , please visit our [Security Reference Page](https://kbve.com/security/)
              - - -
            pr_label: "auto-pr"