on:
    push:
      branches:
      - "beta"
    
jobs:
    pull-request:
      runs-on: ubuntu-latest
      steps:
        - name: pull-request
          uses: actions/checkout@v3
          
        - name: auto-deploy
          uses: diillson/auto-pull-request@v1.0.1
          with:
              destination_branch: "main"                       # If blank, default: master
              pr_title: "Pulling ${{ github.ref }} into Main"  # Title of pull request
              pr_body: |                                        # Full markdown support, requires pr_title to be set
                :crown: *An automated PR*
                Automatic Main Pull
              pr_label: "auto-pr"