name: KBVE Auto Beta <-> Main Pull Request

on:
    push:
      branches:
      - "beta"
    
jobs:
    pull-request:
      runs-on: ubuntu-latest
      steps:
        - name: pull-request
          uses: actions/checkout@v3
          
        - name: auto-deploy
          uses: diillson/auto-pull-request@v1.0.1
          with:
              destination_branch: "main"                      
              pr_title: "Pulling ${{ github.ref }} into Main" 
              pr_body: |                                       
                :crown: *An automated PR*
                Automatic Pull for final stage!
                - - -
                  For Webmaster information please visit our [Webmaster Tools](https://kbve.com/tools/webmaster/)
                - - -
                  Reviewer added: h0lybyte
              pr_label: "auto-pr"
              pr_reviewer: "h0lybyte"